// <auto-generated />
using System;
using LOTA.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LOTA.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250806025142_UpdateApplicationSchema")]
    partial class UpdateApplicationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LOTA.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TutorNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "TUTOR-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7943856f-25f7-4891-beae-b97e7d760244",
                            Email = "tutor1@lota.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "TUTOR1@LOTA.COM",
                            NormalizedUserName = "TUTOR1@LOTA.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c05af296-da86-4254-bf85-baa198390b58",
                            TutorNo = "tutor1@lota.com",
                            TwoFactorEnabled = false,
                            UserName = "tutor1@lota.com"
                        },
                        new
                        {
                            Id = "STUDENT-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d90a5709-01d1-48e6-81fc-244182e185ec",
                            Email = "student1@lota.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT1@LOTA.COM",
                            NormalizedUserName = "STUDENT1@LOTA.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5701eeb3-0e70-4976-bee3-fc2d64acc811",
                            StudentNo = "STUDENT-001",
                            TwoFactorEnabled = false,
                            UserName = "student1@lota.com"
                        });
                });

            modelBuilder.Entity("LOTA.Model.Assignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignment");

                    b.HasData(
                        new
                        {
                            Id = "ASSIGN-001",
                            AssignmentName = "Project Proposal",
                            CourseId = "COURSE-001",
                            CreatedBy = "TUTOR-001",
                            CreatedDate = new DateTime(2025, 8, 6, 14, 51, 41, 956, DateTimeKind.Local).AddTicks(8656),
                            IsActive = true,
                            TotalScore = 100m,
                            TotalWeight = 30m
                        });
                });

            modelBuilder.Entity("LOTA.Model.AssignmentLearningOutcome", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LOId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("LOId");

                    b.ToTable("AssignmentLearningOutcome");

                    b.HasData(
                        new
                        {
                            Id = "ALO1001",
                            AssignmentId = "ASSIGN-001",
                            LOId = "LO-001"
                        },
                        new
                        {
                            Id = "ALO1002",
                            AssignmentId = "ASSIGN-001",
                            LOId = "LO-002"
                        });
                });

            modelBuilder.Entity("LOTA.Model.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = "COURSE-001",
                            CourseCode = "SE101",
                            CourseName = "Software Engineering",
                            CreatedDate = new DateTime(2025, 8, 6, 14, 51, 41, 956, DateTimeKind.Local).AddTicks(8556),
                            Description = "Introduction to software development processes and methodologies.",
                            IsActive = true
                        },
                        new
                        {
                            Id = "COURSE-002",
                            CourseCode = "ST102",
                            CourseName = "Software Testing",
                            CreatedDate = new DateTime(2025, 8, 6, 14, 51, 41, 956, DateTimeKind.Local).AddTicks(8603),
                            Description = "Introduction to software Testing processes and methodologies.",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("LOTA.Model.LearningOutcome", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LOName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("LearningOutcome");

                    b.HasData(
                        new
                        {
                            Id = "LO-001",
                            CourseId = "COURSE-001",
                            CreatedDate = new DateTime(2025, 8, 6, 14, 51, 41, 956, DateTimeKind.Local).AddTicks(8638),
                            Description = "Understand and document software requirements effectively.",
                            LOName = "Requirement Analysis",
                            MaxScore = 100m,
                            Weight = 0.3m
                        },
                        new
                        {
                            Id = "LO-002",
                            CourseId = "COURSE-001",
                            CreatedDate = new DateTime(2025, 8, 6, 14, 51, 41, 956, DateTimeKind.Local).AddTicks(8641),
                            Description = "Apply design principles to create robust software architectures.",
                            LOName = "System Design",
                            MaxScore = 100m,
                            Weight = 0.4m
                        });
                });

            modelBuilder.Entity("LOTA.Model.StudentCourse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourse");

                    b.HasData(
                        new
                        {
                            Id = "STCOURSE-001",
                            CourseId = "COURSE-001",
                            CreatedDate = new DateTime(2025, 8, 6, 14, 51, 41, 956, DateTimeKind.Local).AddTicks(8684),
                            IsActive = true,
                            RegistrationDate = new DateTime(2025, 8, 6, 14, 51, 41, 956, DateTimeKind.Local).AddTicks(8683),
                            StudentId = "STUDENT-001"
                        });
                });

            modelBuilder.Entity("LOTA.Model.StudentScore", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRetake")
                        .HasColumnType("bit");

                    b.Property<string>("LOId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RetakeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("LOId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentScore");

                    b.HasData(
                        new
                        {
                            Id = "SCORE-001",
                            AssignmentId = "ASSIGN-001",
                            CreatedDate = new DateTime(2025, 8, 6, 14, 51, 41, 956, DateTimeKind.Local).AddTicks(8699),
                            IsRetake = false,
                            LOId = "LO-001",
                            Score = 80m,
                            Status = "Pass",
                            StudentId = "STUDENT-001"
                        });
                });

            modelBuilder.Entity("LOTA.Model.TutorCourse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TutorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorCourse");

                    b.HasData(
                        new
                        {
                            Id = "TCO1001",
                            CourseId = "COURSE-001",
                            TutorId = "TUTOR-001"
                        },
                        new
                        {
                            Id = "TCO1002",
                            CourseId = "COURSE-002",
                            TutorId = "TUTOR-001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LOTA.Model.Assignment", b =>
                {
                    b.HasOne("LOTA.Model.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LOTA.Model.AssignmentLearningOutcome", b =>
                {
                    b.HasOne("LOTA.Model.Assignment", "Assignment")
                        .WithMany("AssignmentLearningOutcomes")
                        .HasForeignKey("AssignmentId");

                    b.HasOne("LOTA.Model.LearningOutcome", "LearningOutcome")
                        .WithMany("AssignmentLearningOutcomes")
                        .HasForeignKey("LOId");

                    b.Navigation("Assignment");

                    b.Navigation("LearningOutcome");
                });

            modelBuilder.Entity("LOTA.Model.LearningOutcome", b =>
                {
                    b.HasOne("LOTA.Model.Course", "Course")
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LOTA.Model.StudentCourse", b =>
                {
                    b.HasOne("LOTA.Model.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LOTA.Model.ApplicationUser", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LOTA.Model.StudentScore", b =>
                {
                    b.HasOne("LOTA.Model.Assignment", "Assignment")
                        .WithMany("StudentScores")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LOTA.Model.LearningOutcome", "LearningOutcome")
                        .WithMany()
                        .HasForeignKey("LOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LOTA.Model.ApplicationUser", "Student")
                        .WithMany("StudentScores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("LearningOutcome");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LOTA.Model.TutorCourse", b =>
                {
                    b.HasOne("LOTA.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("LOTA.Model.ApplicationUser", "Tutor")
                        .WithMany("TutorCourse")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LOTA.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LOTA.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LOTA.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LOTA.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LOTA.Model.ApplicationUser", b =>
                {
                    b.Navigation("StudentCourses");

                    b.Navigation("StudentScores");

                    b.Navigation("TutorCourse");
                });

            modelBuilder.Entity("LOTA.Model.Assignment", b =>
                {
                    b.Navigation("AssignmentLearningOutcomes");

                    b.Navigation("StudentScores");
                });

            modelBuilder.Entity("LOTA.Model.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("LearningOutcomes");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("LOTA.Model.LearningOutcome", b =>
                {
                    b.Navigation("AssignmentLearningOutcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
