// <auto-generated />
using System;
using LOTA.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LOTA.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250824103225_updateLOToLOTable")]
    partial class updateLOToLOTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LOTA.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TutorNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "TUTOR-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4257e3b6-7d94-4ff0-a4ac-6095429bda63",
                            Email = "tutor1@lota.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "TUTOR1@LOTA.COM",
                            NormalizedUserName = "TUTOR1@LOTA.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "288cbc95-694f-48c1-a84f-1ac7c4f9bc99",
                            TutorNo = "tutor1@lota.com",
                            TwoFactorEnabled = false,
                            UserName = "tutor1@lota.com"
                        },
                        new
                        {
                            Id = "STUDENT-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4adf72c-0265-4828-90f8-dacf0fe1fa6c",
                            Email = "student1@lota.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT1@LOTA.COM",
                            NormalizedUserName = "STUDENT1@LOTA.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf19a088-8efc-443b-97a4-88cf091a1d54",
                            StudentNo = "STUDENT-001",
                            TwoFactorEnabled = false,
                            UserName = "student1@lota.com"
                        });
                });

            modelBuilder.Entity("LOTA.Model.Assessment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssessmentTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseOfferingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TrimesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentTypeId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("TrimesterId");

                    b.ToTable("Assessment");

                    b.HasData(
                        new
                        {
                            Id = "ASSIGN-001",
                            AssessmentName = "Project Proposal",
                            AssessmentTypeId = "001",
                            CourseOfferingId = "TC001",
                            CreatedBy = "TUTOR-001",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(138),
                            IsActive = true,
                            TotalScore = 100m,
                            TotalWeight = 30m,
                            TrimesterId = "Trimester-001"
                        });
                });

            modelBuilder.Entity("LOTA.Model.AssessmentLearningOutcome", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LOId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("LOId");

                    b.ToTable("AssessmentLearningOutcome");

                    b.HasData(
                        new
                        {
                            Id = "ALO1001",
                            AssessmentId = "ASSIGN-001",
                            LOId = "LO-001"
                        },
                        new
                        {
                            Id = "ALO1002",
                            AssessmentId = "ASSIGN-001",
                            LOId = "LO-002"
                        });
                });

            modelBuilder.Entity("LOTA.Model.AssessmentType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessmentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AssessmentType");

                    b.HasData(
                        new
                        {
                            Id = "001",
                            AssessmentTypeName = "Assignment"
                        },
                        new
                        {
                            Id = "002",
                            AssessmentTypeName = "Exam"
                        },
                        new
                        {
                            Id = "003",
                            AssessmentTypeName = "Test"
                        },
                        new
                        {
                            Id = "004",
                            AssessmentTypeName = "Project"
                        },
                        new
                        {
                            Id = "005",
                            AssessmentTypeName = "Presentation"
                        });
                });

            modelBuilder.Entity("LOTA.Model.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QualificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = "COURSE-001",
                            CourseCode = "SE101",
                            CourseName = "Software Engineering",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 130, DateTimeKind.Local).AddTicks(9954),
                            Description = "Introduction to software development processes and methodologies.",
                            IsActive = true,
                            QualificationId = "Qualification-001"
                        },
                        new
                        {
                            Id = "COURSE-002",
                            CourseCode = "ST102",
                            CourseName = "Software Testing",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 130, DateTimeKind.Local).AddTicks(9959),
                            Description = "Introduction to software Testing processes and methodologies.",
                            IsActive = true,
                            QualificationId = "Qualification-002"
                        });
                });

            modelBuilder.Entity("LOTA.Model.LearningOutcome", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LOName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("LearningOutcome");

                    b.HasData(
                        new
                        {
                            Id = "LO-001",
                            CourseId = "COURSE-001",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(76),
                            Description = "Understand and document software requirements effectively.",
                            LOName = "Requirement Analysis"
                        },
                        new
                        {
                            Id = "LO-002",
                            CourseId = "COURSE-001",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(79),
                            Description = "Apply design principles to create robust software architectures.",
                            LOName = "System Design"
                        });
                });

            modelBuilder.Entity("LOTA.Model.Qualification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("QualificationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QualificationTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QualificationTypeId");

                    b.ToTable("Qualification");

                    b.HasData(
                        new
                        {
                            Id = "Qualification-001",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 130, DateTimeKind.Local).AddTicks(9862),
                            IsActive = true,
                            Level = 7,
                            QualificationName = "Bachelor of Information Technolog",
                            QualificationTypeId = "001"
                        },
                        new
                        {
                            Id = "Qualification-002",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 130, DateTimeKind.Local).AddTicks(9923),
                            IsActive = true,
                            Level = 5,
                            QualificationName = "Diploma in IT Technical Support",
                            QualificationTypeId = "002"
                        });
                });

            modelBuilder.Entity("LOTA.Model.QualificationType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QualificationTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("QualificationType");

                    b.HasData(
                        new
                        {
                            Id = "001",
                            QualificationTypeName = "Bachelor"
                        },
                        new
                        {
                            Id = "002",
                            QualificationTypeName = "Diploma"
                        },
                        new
                        {
                            Id = "003",
                            QualificationTypeName = "Certificate"
                        },
                        new
                        {
                            Id = "004",
                            QualificationTypeName = "Master"
                        },
                        new
                        {
                            Id = "005",
                            QualificationTypeName = "PhD"
                        },
                        new
                        {
                            Id = "006",
                            QualificationTypeName = "Graduate Diploma"
                        },
                        new
                        {
                            Id = "007",
                            QualificationTypeName = "Postgraduate Diploma"
                        },
                        new
                        {
                            Id = "008",
                            QualificationTypeName = "Postgraduate Certificate"
                        });
                });

            modelBuilder.Entity("LOTA.Model.StudentCourse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseOfferingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrimesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrimesterId");

                    b.ToTable("StudentCourse");

                    b.HasData(
                        new
                        {
                            Id = "STCOURSE-001",
                            CourseOfferingId = "TC001",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(188),
                            IsActive = true,
                            RegistrationDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(186),
                            StudentId = "STUDENT-001",
                            TrimesterId = "Trimester-001"
                        });
                });

            modelBuilder.Entity("LOTA.Model.StudentScore", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRetake")
                        .HasColumnType("bit");

                    b.Property<string>("LOId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RetakeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrimesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("LOId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrimesterId");

                    b.ToTable("StudentScore");

                    b.HasData(
                        new
                        {
                            Id = "SCORE-001",
                            AssessmentId = "ASSIGN-001",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(215),
                            IsRetake = false,
                            LOId = "LO-001",
                            Score = 80m,
                            Status = "Pass",
                            StudentId = "STUDENT-001",
                            TrimesterId = "Trimester-001"
                        });
                });

            modelBuilder.Entity("LOTA.Model.Trimester", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TrimesterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Trimester");

                    b.HasData(
                        new
                        {
                            Id = "Trimester-001",
                            AcademicYear = 2024,
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(13),
                            IsActive = true,
                            TrimesterNumber = 1
                        },
                        new
                        {
                            Id = "Trimester-002",
                            AcademicYear = 2024,
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(18),
                            IsActive = true,
                            TrimesterNumber = 2
                        },
                        new
                        {
                            Id = "Trimester-003",
                            AcademicYear = 2025,
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(20),
                            IsActive = true,
                            TrimesterNumber = 1
                        },
                        new
                        {
                            Id = "Trimester-004",
                            AcademicYear = 2025,
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(23),
                            IsActive = true,
                            TrimesterNumber = 2
                        });
                });

            modelBuilder.Entity("LOTA.Model.TrimesterCourse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrimesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TutorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TrimesterId");

                    b.HasIndex("TutorId");

                    b.ToTable("TrimesterCourse");

                    b.HasData(
                        new
                        {
                            Id = "TC001",
                            CourseId = "COURSE-001",
                            CreatedDate = new DateTime(2025, 8, 24, 22, 32, 22, 131, DateTimeKind.Local).AddTicks(50),
                            IsActive = true,
                            TrimesterId = "Trimester-001",
                            TutorId = "TUTOR-001"
                        });
                });

            modelBuilder.Entity("LOTA.Model.TutorCourse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TutorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorCourse");

                    b.HasData(
                        new
                        {
                            Id = "TCO1001",
                            CourseId = "COURSE-001",
                            TutorId = "TUTOR-001"
                        },
                        new
                        {
                            Id = "TCO1002",
                            CourseId = "COURSE-002",
                            TutorId = "TUTOR-001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LOTA.Model.Assessment", b =>
                {
                    b.HasOne("LOTA.Model.AssessmentType", "AssessmentType")
                        .WithMany("Assessments")
                        .HasForeignKey("AssessmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LOTA.Model.Course", null)
                        .WithMany("Assessments")
                        .HasForeignKey("CourseId");

                    b.HasOne("LOTA.Model.TrimesterCourse", "TrimesterCourse")
                        .WithMany()
                        .HasForeignKey("CourseOfferingId");

                    b.HasOne("LOTA.Model.Trimester", "Trimester")
                        .WithMany()
                        .HasForeignKey("TrimesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentType");

                    b.Navigation("Trimester");

                    b.Navigation("TrimesterCourse");
                });

            modelBuilder.Entity("LOTA.Model.AssessmentLearningOutcome", b =>
                {
                    b.HasOne("LOTA.Model.Assessment", "Assessment")
                        .WithMany("AssessmentLearningOutcomes")
                        .HasForeignKey("AssessmentId");

                    b.HasOne("LOTA.Model.LearningOutcome", "LearningOutcome")
                        .WithMany("AssessmentLearningOutcomes")
                        .HasForeignKey("LOId");

                    b.Navigation("Assessment");

                    b.Navigation("LearningOutcome");
                });

            modelBuilder.Entity("LOTA.Model.Course", b =>
                {
                    b.HasOne("LOTA.Model.Qualification", "Qualification")
                        .WithMany("Courses")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("LOTA.Model.LearningOutcome", b =>
                {
                    b.HasOne("LOTA.Model.Course", "Course")
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LOTA.Model.Qualification", b =>
                {
                    b.HasOne("LOTA.Model.QualificationType", "QualificationType")
                        .WithMany("Qualifications")
                        .HasForeignKey("QualificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QualificationType");
                });

            modelBuilder.Entity("LOTA.Model.StudentCourse", b =>
                {
                    b.HasOne("LOTA.Model.Course", null)
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId");

                    b.HasOne("LOTA.Model.TrimesterCourse", "TrimesterCourse")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LOTA.Model.ApplicationUser", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LOTA.Model.Trimester", "Trimester")
                        .WithMany()
                        .HasForeignKey("TrimesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Trimester");

                    b.Navigation("TrimesterCourse");
                });

            modelBuilder.Entity("LOTA.Model.StudentScore", b =>
                {
                    b.HasOne("LOTA.Model.Assessment", "Assessment")
                        .WithMany("StudentScores")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LOTA.Model.LearningOutcome", "LearningOutcome")
                        .WithMany()
                        .HasForeignKey("LOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LOTA.Model.ApplicationUser", "Student")
                        .WithMany("StudentScores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LOTA.Model.Trimester", "Trimester")
                        .WithMany()
                        .HasForeignKey("TrimesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("LearningOutcome");

                    b.Navigation("Student");

                    b.Navigation("Trimester");
                });

            modelBuilder.Entity("LOTA.Model.TrimesterCourse", b =>
                {
                    b.HasOne("LOTA.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LOTA.Model.Trimester", "Trimester")
                        .WithMany()
                        .HasForeignKey("TrimesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LOTA.Model.ApplicationUser", "Tutor")
                        .WithMany("TrimesterCourse")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Trimester");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("LOTA.Model.TutorCourse", b =>
                {
                    b.HasOne("LOTA.Model.Course", "Course")
                        .WithMany("TutorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LOTA.Model.ApplicationUser", "Tutor")
                        .WithMany("TutorCourse")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LOTA.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LOTA.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LOTA.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LOTA.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LOTA.Model.ApplicationUser", b =>
                {
                    b.Navigation("StudentCourses");

                    b.Navigation("StudentScores");

                    b.Navigation("TrimesterCourse");

                    b.Navigation("TutorCourse");
                });

            modelBuilder.Entity("LOTA.Model.Assessment", b =>
                {
                    b.Navigation("AssessmentLearningOutcomes");

                    b.Navigation("StudentScores");
                });

            modelBuilder.Entity("LOTA.Model.AssessmentType", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("LOTA.Model.Course", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("LearningOutcomes");

                    b.Navigation("StudentCourses");

                    b.Navigation("TutorCourses");
                });

            modelBuilder.Entity("LOTA.Model.LearningOutcome", b =>
                {
                    b.Navigation("AssessmentLearningOutcomes");
                });

            modelBuilder.Entity("LOTA.Model.Qualification", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LOTA.Model.QualificationType", b =>
                {
                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("LOTA.Model.TrimesterCourse", b =>
                {
                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
